DROP DATABASE IF EXISTS greatBay_DB;

CREATE DATABASE greatBay_DB;

USE greatBay_DB;

CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  quantity INT NOT NULL ,
  bidPrice DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (id)
);
